# tablist
[plugin]
    enabled=true

# Global tablist
[global-tablist]
    enabled=true

[tablist-header-footer]
    enabled=true
    # If you are unsure how to hanle new lines, take a look at https://toml.io/en/ or just use \n
    header="""
        <white>SkeletonTAB</white>

        <white>Hi there! The globle tablist</white>"""
    footer="<light_purple>Good job!</light_purple>"